### PR TITLE
Added new trigger for On Device Changed

### LINKED ISSUE #648: Profile trigger for when devices are changed by Windows
**Is your feature request related to a problem? Please describe.**
Windows has a "feature" where it will change the audio input and output devices when you plug in a device. I've got my devices set as I need but there's no way to disable the feature.

**Describe the solution you'd like**
I've started using SoundSwitch to make it easier to change from a hotkey but if there were a feature to automatically apply a profile when Windows decides to change inputs, it would be awesome.

**Describe alternatives you've considered**
I've not found a tool to make this better or disable the feature. SoundSwitch makes this way more tolerable, so I appreciate it!

### PR DESCRIPTION
**Pull request by codemann8**
I'm not sure if this is desired upstream. But I added a new trigger for when the Default Sound Device changes. Many people on Windows 10 hate how plugging in new devices will automatically change the Default Device. This change will ensure that a device of the user's choosing will always be the active sound device.

This has not been tested extensively in conjunction with other triggers and profiles.  But this change suits my needs and if it is helpful upstream, you're free to use it and tailor it to whatever end. It also is missing Localization for non-English languages.

Resolves #648

### CODE REVIEW

**Comment by Belphemur** [comment]
Interesting feature.

So basically it's a force profile. To be sure that whatever happens those device stay the default one.

**Comment by Belphemur** [comment]
@all-contributors please add @codemann8  for code

**Comment by codemann8** [comment]
That would be a good name too. I'll prob leave it as is. But if you desired a certain name or other changes upstream, by all means make the changes you see best for the product.

**Comment by Belphemur** [comment]
Thanks for the feature :)

This will be available in the next release, and already in the nightly one.

**Pull request merged**
