### PR TITLE
fix(QuickMenu): Take into account the edge of the screen and show the quick menu properly

### PR DESCRIPTION
**Pull request by lpv-repo**
Fix QuickMenu going off-screen

### CODE REVIEW

**Comment by lpv-repo** [comment]
Sorry for multiple commits, after the first one the rest 2 were unintentional.

**Comment by Belphemur** [comment]
Hello,

Thanks for this !
I'll try it out ASAP and for the commits it's okay, I'll squash them :)

**Comment by Belphemur** [comment]
Works perfectly!
LGTM

**Comment by Belphemur** [comment]
@all-contributors please add @lpv11 for code

**Comment by Belphemur** [comment]
@all-contributors please add @lpv11 for code

**Pull request merged**
