### PR TITLE
Fix Icon

### PR DESCRIPTION
**Pull request by Belphemur**
I've redone completely the Icon.

I based it on the new logo and the old one. I think it turned quite nice

logosoundswitch-16

logosoundswitch-big

### CODE REVIEW

**Comment by Belphemur** [comment]
@alystair  & @FireEmerald What do you think of this version ?

**Comment by FireEmerald** [comment]
I think the image is a bit to noisy/restless. I would add a white border to the default icon, example:

- win10
- white-bg  (white background)

**Comment by Belphemur** [comment]
I see what you mean.

The problem I have with the new logo is the lack of readability when it's 16x16.
In it's original form, it's awesome. But as an Icon, can you really tell it's "Sound-Wave-Switch" ?

With the one I made, the Switch part is clear, the sound part a little less. It's a bit of both logos.

**Comment by alystair** [comment]
definitely an improvement, but still lacks the cleanliness of the original - one doesn't have to represent an entire concept in an icon, just having the "Switch" element of SoundSwitch makes enough sense to me :)

**Comment by Belphemur** [comment]
@alystair  & @FireEmerald 
Here is the new logo that I just made 
small

soundswitchlogo

This is the best I came up with. I took back the previous arrow, went for blue, and added a speaker.

It's quite readable in the systray and should be visible on Windows 7 too.

**Pull request merged**
