### PR TITLE
Improved the multi-language support, this includes:

### LINKED ISSUE #156: Localization improvements
I was looking inside your code for the localization and thought it would be more or less easy possible to add another language for SoundSwitch. If this is no problem for you @Belphemur i will add **German** as 3rd one.

While adding the new `*.de.resx` files, i'm going to change some names of various controls to get a more consistent naming. This will provide in the future a easier way to implement even more languages.

I'm sure there are also some untranslated strings - like those from the new update settings. I will also add these to the existing resource files as well as some typo fixes ;)

When it's done, I will create a pull request. (next few days)

### PR DESCRIPTION
**Pull request by FireEmerald**
- Added the possibility to specify which language is used. The specified language is saved in the configuration.
- If a new/empty or older configuration is present without a specified language, the language is automatically determined based on the system language. If the system language is supported by SoundSwitch this language is used. If not, English is used.
- The language is loaded once at startup. If it's changed later inside the settings form a restart of the application is required.
- Added German as third supported language.

Code relevant changes:
- New directory for all localization files /Localization.
- Moved all control localizations from the *.Designer.cs files to it's own methods outside of the *.Designer.cs files.
- Naming for all localizations is lowerCamelCase.
- While updating the localizations i also changed some English texts. As a result these strings are untranslated now in French.
- Tweaked some labels to support a different length - that's important if a string is in another language longer then in English.

Important:
- If ANY text inside the forms (designer) is changer or the other way around any English texts inside the *.resx files - they needed to be synchronized!

Other by-the-way changes:
- Minor code-style changes in various files which doesn't affect the functionality.
- Synchronized all file headers and updated copyright notices.

ToDo's after this PR is merged:
- Create wiki article how language changes should be done.
- Translate missing french strings (@Belphemur).

Fixes #156.

### CODE REVIEW

**Comment by Belphemur** [comment]
I'll check it thoroughly this weekend.

**Comment by FireEmerald** [comment]
You may already noticed that i planed to write a short article how new languages are implemented, because no one know's after this commit that we used Zeta.

So i included a link inside the new README.md file which point's to a non-existing wiki page. I already created it inside my fork to show you what i was thinking about: https://github.com/FireEmerald/SoundSwitch/wiki/Add-or-modify-another-language

**Comment by Belphemur** [comment]
I enabled the wiki on the repository.

I'm merging it, If my memory is right the Wiki is editable by everybody.

**Comment by Belphemur** [comment]
@all-contributors please add @FireEmerald for code, translation, Documentation

**Pull request merged**
